export const SET_TRAVEL_MODE = "SET_TRAVEL_MODE";
export const SET_INITIAL = "SET_INITIAL";
export const SET_ORIGIN_INPUT = "SET_ORIGIN_INPUT";
export const SET_DEST_INPUT = "SET_DEST_INPUT";
export const SET_DEPT_INPUT = "SET_DEPT_INPUT";
export const SET_RETURN_INPUT = "SET_RETURN_INPUT";
export const SET_PASSENGER_INPUT = "SET_PASSENGER_INPUT";
export const SEARCH_FLIGHT = "SEARCH_FLIGHT";